export function debounce(fn : (arg : any) => void,d : number = 300) {
    let timer : any = null;
    return function(){
      clearTimeout(timer);
      timer=setTimeout(fn,d);
    }
  }
  export const mapWilayas = {
    Adrar: { value: 120 },
    Alger: { value: 60 },
    Annaba: { value: 10 },
    "Aïn Defla": { value: 30 },
    "Aïn Témouchent": { value: 20 },
    Batna: { value: 40 },
    Biskra: { value: 50 },
    Blida: { value: 70 },
    "Bordj Badji Mokhtar": { value: 80 },
    "Bordj Bou Arréridj": { value: 90 },
    Bouira: { value: 100 },
    Boumerdès: { value: 110 },
    Béchar: { value: 130 },
    Béjaïa: { value: 140 },
    "Béni Abbès": { value: 150 },
    Chlef: { value: 160 },
    Constantine: { value: 170 },
    Djanet: { value: 180 },
    Djelfa: { value: 190 },
    "El Bayadh": { value: 200 },
    "El Meghaier": { value: 210 },
    "El Menia": { value: 220 },
    "El Oued": { value: 230 },
    "El Tarf": { value: 240 },
    Ghardaïa: { value: 250 },
    Guelma: { value: 260 },
    Illizi: { value: 270 },
    "In Guezzam": { value: 280 },
    "In Salah": { value: 290 },
    Jijel: { value: 300 },
    Khenchela: { value: 310 },
    Laghouat: { value: 320 },
    "M'Sila": { value: 330 },
    Mascara: { value: 340 },
    Mila: { value: 350 },
    Mostaganem: { value: 360 },
    Médéa: { value: 370 },
    Naâma: { value: 380 },
    Oran: { value: 390 },
    Ouargla: { value: 400 },
    "Ouled Djellal": { value: 41 },
    "Oum El Bouaghi": { value: 42 },
    Relizane: { value: 483 },
    Saïda: { value: 144 },
    "Sidi Bel Abbès": { value: 45 },
    Skikda: { value: 406 },
    "Souk Ahras": { value: 47 },
    Sétif: { value: 498 },
    Tamanrasset: { value: 49 },
    Tiaret: { value: 50 },
    Timimoun: { value: 51 },
    Tindouf: { value: 52 },
    Tipaza: { value: 53 },
    Tissemsilt: { value: 54 },
    "Tizi Ouzou": { value: 55 },
    Tlemcen: { value: 56 },
    Touggourt: { value: 57 },
    Tébessa: { value: 58 },
  };
export const wilayas =[
    "Adrar",
    "Chlef",
    "Laghouat",
    "Oum El Bouaghi",
    "Batna",
    "Béjaïa",
    "Biskra",
    "Béchar",
    "Blida",
    "Bouira",
    "Tamanrasset",
    "Tébessa",
    "Tlemcen",
    "Tiaret",
    "Tizi Ouzou",
    "Alger",
    "Djelfa",
    "Jijel",
    "Sétif",
    "Saïda",
    "Skikda",
    "Sidi Bel Abbès",
    "Annaba",
    "Guelma",
    "Constantine",
    "Médéa",
    "Mostaganem",
    "M'Sila",
    "Mascara",
    "Ouargla",
    "Oran",
    "El Bayadh",
    "Illizi",
    "Bordj Bou Arréridj",
    "Boumerdès",
    "El Tarf",
    "Tindouf",
    "Tissemsilt",
    "El Oued",
    "Khenchela",
    "Souk Ahras",
    "Tipaza",
    "Mila",
    "Aïn Defla",
    "Naâma",
    "Aïn Témouchent",
    "Ghardaïa",
    "Relizane",
    "Timimoun",
    "Bordj Badji Mokhtar",
    "Ouled Djellal",
    "Béni Abbès",
    "In Salah",
    "In Guezzam",
    "Touggourt",
    "Djanet",
    "El M'Ghair",
    "El Menia"
]
export const mapWilayasIndexes = Object.keys(mapWilayas);

